// Copyright 2026 veilbrowser contributors
// Use of this source code is governed by the MIT license found in the
// repository LICENSE (Chromium upstream remains BSD-style).
//
// Compiled-in veilbrowser fingerprint payload. Generated by
// scripts/gen_native_patch.py — regenerate, never hand-edit.

#ifndef CHROME_RENDERER_VEIL_VEIL_BUNDLE_H_
#define CHROME_RENDERER_VEIL_VEIL_BUNDLE_H_

namespace veil {

// Bundle template (prelude + script) carrying two substitution slots:
// __VEIL_PARAMS_JSON__ (per-profile parameters, small JSON) and
// __VEIL_CFG__ (the cfg expression inside the bundle IIFE).
extern const char kVeilScriptTemplate[];

// Metric-compatible clone fonts per platform as data:-URL woff2,
// {"windows": {...}, "macos": {...}, "linux": {...}}.
extern const char kVeilFontData[];

}  // namespace veil

#endif  // CHROME_RENDERER_VEIL_VEIL_BUNDLE_H_
